name: shellcheck

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  shellcheck:
    name: Run shellcheck on scripts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.0.0

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
